version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: "./Dockerfile"
    working_dir: /var/www/
    container_name: password-app    
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "8000:5173"
    networks:
      - password-network
    volumes:
      - ./:/var/www/
networks:
  password-network:
    driver: bridge
