version: "3.3"
services:
  password:
    build:
      context: .
      dockerfile: "./Dockerfile"
    working_dir: /go/src/${ENV_SRC}
    container_name: password-go
    stdin_open: true
    tty: true
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - password-network
    volumes:
      - ./:/go/src/${ENV_SRC}
networks:
  password-network:
    driver: bridge
